---
title: "Código"
author: "Guillermo Pinto"
date: "2023-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preparación de datos

### Importación de datos

```{r import_data}
ruta_datos <- "SB11_20222.csv"
data <- read.csv(ruta_datos, sep = ",", dec = ".", header = TRUE, stringsAsFactors = FALSE)
# Verificar la clase del objeto
class(data)
# Ver los nombres de las columnas
colnames(data)
# Contar la cantidad de registros y columnas
dim(data)
```

### Limpieza

```{r clean_data}
columnas_irrelevantes <- c(
    "FAMI_PERSONASHOGAR", "FAMI_CUARTOSHOGAR", "FAMI_TRABAJOLABORPADRE", 
    "FAMI_TRABAJOLABORMADRE", "FAMI_COMELECHEDERIVADOS", "FAMI_COMECARNEPESCADOHUEVO", 
    "FAMI_COMECEREALFRUTOSLEGUMBRE", "ESTU_TIPODOCUMENTO", "ESTU_NACIONALIDAD", 
    "ESTU_FECHANACIMIENTO", "PERIODO", "ESTU_CONSECUTIVO", "ESTU_ESTUDIANTE", 
    "ESTU_PAIS_RESIDE", "ESTU_PRIVADO_LIBERTAD", "ESTU_COD_MCPIO_PRESENTACION", 
    "ESTU_MCPIO_PRESENTACION", "ESTU_DEPTO_PRESENTACION", "ESTU_COD_DEPTO_PRESENTACION", 
    "ESTU_INSE_INDIVIDUAL", "ESTU_ESTADOINVESTIGACION", "COLE_CODIGO_ICFES", 
    "COLE_COD_DANE_ESTABLECIMIENTO", "COLE_NOMBRE_ESTABLECIMIENTO", "COLE_GENERO", 
    "COLE_CALENDARIO", "COLE_CARACTER", "COLE_COD_DANE_SEDE", "COLE_NOMBRE_SEDE", 
    "COLE_SEDE_PRINCIPAL", "COLE_JORNADA", "PUNT_LECTURA_CRITICA", 
    "PERCENTIL_LECTURA_CRITICA", "PUNT_MATEMATICAS", "PERCENTIL_MATEMATICAS", 
    "PUNT_C_NATURALES", "PERCENTIL_C_NATURALES", "PUNT_SOCIALES_CIUDADANAS", 
    "PERCENTIL_SOCIALES_CIUDADANAS", "PUNT_INGLES", "PERCENTIL_INGLES"
)

data <- data[, !names(data) %in% columnas_irrelevantes]
# Contar la cantidad de registros y columnas
dim(data)
```

### Previsualización
```{r prev_data}
# Tabla con los datos limpios
#install.packages("DT")
library(DT)
# Muestra las primeras 50 filas con solo 10 columnas
datatable(head(datos_limpios[, 1:10],50))
```

### Diccionario de datos 

```{r dicc_data}
# Diccionario de datos
Variable.type <- lapply(data,class)
Variable.desc <- c(
    "Género",
    "¿Pertenece usted a un grupo étnico minoritario?",
    "Departamento de residencia",
    "Código Dane del departamento de residencia",
    "Municipio de Residencia",
    "Código Dane del municipio de residencia",
    "Nivel educativo más alto alcanzado por el padre",
    "Nivel educativo más alto alcanzado por la madre",
    "Estrato socioeconómico de la vivienda según recibo de energía eléctrica",
    "¿Su hogar cuenta con servicio o conexión a internet?",
    "¿Cuáles de los siguientes bienes posee su hogar?: Computador",
    "¿Cuáles de los siguientes bienes posee su hogar?: Máquina lavadora de ropa",
    "¿Cuáles de los siguientes bienes posee su hogar?: Horno Microondas u Horno eléctrico o a gas",
    "¿Su hogar cuenta con servicio cerrado de televisión?",
    "¿Cuáles de los siguientes bienes posee su hogar?: Automóvil particular",
    "¿Cuáles de los siguientes bienes posee su hogar?: Motocicleta",
    "¿Cuáles de los siguientes bienes posee su hogar?: Consola para juegos electrónicos (PlayStation, Xbox, Nintendo, etc.)",
    "¿Cuántos libros físicos o electrónicos hay en su hogar excluyendo periódicos, revistas, directorios telefónicos y libros del colegio?",
    "Usualmente, ¿cuánto tiempo al día dedica a leer por entretenimiento?",
    "Usualmente, ¿cuánto tiempo al día dedica a navegar en internet? Excluya actividades académicas",
    "¿Cuántas horas trabajó usted durante la semana pasada?",
    "¿Usted recibe algún tipo de remuneración por trabajar?",
    "Con respecto al año inmediatamente anterior, la situación económica de su hogar es:",
    "Indica la naturaleza del Establecimiento (Privado o público)",
    "Indica si el Establecimiento es bilingüe o no",
    "Área de ubicación de la Sede (rural o urbano)",
    "Código Dane del municipio donde está ubicada la Sede",
    "Nombre del municipio donde está ubicada la Sede",
    "Código Dane del departamento de la Sede",
    "Nombre del departamento donde está ubicada la Sede",
    "Desempeño matemáticas",
    "Desempeño en inglés",
    "Desempeño ciencias naturales",
    "Desempeño en lectura crítica",
    "Desempeño sociales y ciudadanas",
    "Puntaje total obtenido",
    "Percentil global en que se encuentra el evaluado",
    "Nivel Socioeconómico del evaluado",
    "Nivel Socioeconómico del Establecimiento"
)
data.desc <- as.data.frame(cbind(Data.Type = unlist(Variable.type), 
                                 Variable.Description = Variable.desc))
colnames(data.desc) <- c("Data Type","Variable Description")
library(knitr)
kable(data.desc)
```

## Data analisys

### Socioeconomico
#### Correlación entre el desempeño académico y el nivel socioeconómico del estudiante

```{r cor_nse_punt}
nuevo_df <- data[, c("ESTU_NSE_INDIVIDUAL", "PUNT_GLOBAL")] # Crear un nuevo dataframe con las dos columnas de interés

sum(is.na(nuevo_df)) # Contar la cantidad de NA

nuevo_df <- nuevo_df[complete.cases(nuevo_df), ] # Quitar los NA del nuevo dataframe

sum(is.na(nuevo_df)) # Contar la cantidad de NA

# Calcular matriz de correlación
correlation_matrix <- cor(nuevo_df$ESTU_NSE_INDIVIDUAL, nuevo_df$PUNT_GLOBAL)

# Gráfico de dispersión
plot(nuevo_df$ESTU_NSE_INDIVIDUAL, nuevo_df$PUNT_GLOBAL,
     xlab = "Nivel Socioeconómico Individual",
     ylab = "Puntaje Global",
     main = "Gráfico de dispersión")

# Gráfico de regresión
plot(nuevo_df$ESTU_NSE_INDIVIDUAL, nuevo_df$PUNT_GLOBAL,
     xlab = "Nivel Socioeconómico Individual",
     ylab = "Puntaje Global",
     main = "Gráfico de regresión")
abline(lm(PUNT_GLOBAL ~ ESTU_NSE_INDIVIDUAL, data = nuevo_df), col = "red")

# Gráfico de densidad conjunta
ggplot2::ggplot(nuevo_df, aes(x = ESTU_NSE_INDIVIDUAL, y = PUNT_GLOBAL)) +
    geom_density_2d() +
    labs(x = "Nivel Socioeconómico Individual", y = "Puntaje Global") +
    ggtitle("Gráfico de Densidad Conjunta")

library(ggplot2)

ggplot(nuevo_df, aes(x = nuevo_df$ESTU_NSE_INDIVIDUAL, y = nuevo_df$PUNT_GLOBAL)) +
    geom_jitter()


ggplot(nuevo_df, aes(x = nuevo_df$ESTU_NSE_INDIVIDUAL, y = nuevo_df$PUNT_GLOBAL)) +
    geom_point() +
    stat_smooth()
```